name: Release (master)
on:
  push:
    branches:
      - 3.9test
concurrency:
  group: release-master
permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      prerelease: true
      source: 3.9test
    permissions:
      contents: write
      packages: write  # For package cache
      actions: write  # For cleaning up cache
      id-token: write  # mandatory for trusted publishing
    secrets: inherit
