name: Release (macos)
on:
  push:
    branches:
      - macos
concurrency:
  group: release-macos
permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      prerelease: true
      source: macos
    permissions:
      contents: write
      packages: write
      id-token: write  # mandatory for trusted publishing
    secrets: inherit
